### ISSUE TITLE
Provide abstractions over common record types.

### ISSUE THREAD

**Issue by PaulusParssinen** [OpenWilma/openwilma_dotnet#6]
Wilma has the most inconsistent API schema I have ever come across. This requires us to do dirty-tricks to make the API more developer friendly such as the `NestedArrayConverter` to handle ugly hierarchy of the legacy APIs for simple arrays. We should move to newer endpoints (#5).

We should attempt to create some abstractions over the common user group properties and various reoccurring patterns. These will probably involve some custom S.T.Json converters folding and flatteting types as the Wilma API just _splats_ all fields into flat object. One step further could be to generate these using Source Generators at the build-time but I'll investigate simpler `JsonConverter` options first. This all may not even be necessary because I have yet to investigate the newer endpoints and with quick skim they seem to have improved things.

## TODO
* [ ] Provide interfaces for common user groups/roles.
* [ ] Investigate whats the state of Wilma API support. SaaS model _should_ have them pretty consistent and up-to-date hopefully.
* [ ] etc. Try recognize "Start"/"End" patterns for date related fields.
